export const SERVER_INSTRUCTIONS = [
  "Private local IPQS MCP for text-first dashboard inspection, confirmation-gated low-risk account preference changes, API-key import into an ignored owner-only file, and official read-only JSON API calls.",
  "Use the official API for account usage and reputation lookups without opening a browser. Reserve the dedicated real Chrome/CDP profile for dashboard-only evidence or account actions. A task may explicitly authorize one bounded login from the fixed owner-only two-line credential bundle; CAPTCHA, email verification, passkeys, and 2FA remain human-auth steps in the visible browser.",
  "Saved credential values and paths never enter MCP inputs or outputs. Do not retry a failed saved login automatically, and do not read the bundle when the dedicated profile is already authenticated.",
  "Never return or log API keys, passwords, cookies, localStorage, browser-profile data, raw session state, hidden form values, or private account identifiers.",
  "Dashboard reads default to one bounded same-origin GET inside the dedicated session and inert HTML text extraction, without page navigation/rendering. Use mode=controls for rendered DOM and value-free control metadata; text mode is not proof of rendered visibility. API-key import writes the selected visible key directly to the configured private secret file and returns only a fingerprint.",
  "Account preference changes use a short-lived prepare/apply flow, exact field matching, an allowlisted control policy, a safe submit label, and the literal apply confirmation. Password, email, MFA, billing, subscription, deletion, and API-key lifecycle changes are excluded from that generic setting tool.",
  "Official API calls are GET-only: reputation lookups use the ipqs-key header, while account usage uses the documented credential-in-path endpoint internally. Never return either credential or request URL. Reject redirects and oversized or non-JSON responses; never retry a lookup automatically because retries can consume credits. HTTP failures cannot prove authentication; insufficient credits alone does not identify a duplicate-account restriction.",
  "Do not enable or register this MCP in live Codex config unless the task explicitly requests it and the login/recovery boundary has been reviewed.",
  "Read package AGENTS.md before changing browser, dashboard mutation, secret-file, or API behavior.",
].join("\n");
